pages/company/index.html
=> rm teradata

_data/authors.yml, _posts/2017-04-28-introducing-factotum-server.md, pages/blog/authors/nicholas.html
Factotum Server 0.1.0 Release blog post.
Includes additional fixes for #130. Also updated avatars to static assets in line with new website changes.
=> Posts/factotum server 0.1.0

_posts/2017-05-08-snowplow-meetup-amsterdam-#3-was-all-about-personalisation-across-the-customer-journey.md
Added links to Getninjas and Creditas websites
=> Posts/snowplow amsterdam meetup #3

pages/customers/peak/index.html
Revised Peak case study web page (take 2)
=> Peak case study web page revision take 2

pages/customers/viewbix/index.html
Created Viewbix case study web page (copy)
=> Viewbix case study web page

_posts/2017-08-17-snowplow-r91-stonehenge-released-with-important-bug-fix.md
@alexanderdean I think those are the issues you wanted to link?
=> Fixed issue links

pages/customers/index.html
Minor correction on the branch regarding block spacings on the Customers page.
=> Customer Page - Picnic Case Study spacing correction

pages/partners/implementation/index.html, pages/partners/index.html
=> Partners - Image path correction

_posts/2017-10-18-snowplow-scala-tracker-released/index.md
Migrated from https://github.com/snowplow/snowplowanalytics.com/pull/336
Hey @yalisassoon this is ready. Just updated the date.
=> Add Scala Tracker 0.4.0 post

pages/customers/peak/index.html
Thomas requested we change '...and make people smarter' for legal reasons. Updated title and description of Peak case study to "How Peak uses Snowplow to build award winning games that train cognitive skills."
=> Updating Peak case study as per Thomas' request

_includes/header.html
add ID to javascript for Request a Demo button
=> Ed's changes to Request a Demo button

pages/company/index.html
=> Mnrq 366 add users

_posts/2017-12-11-away-week-prague/index.md
Added Away Week Prague blog post as well as associated images in the assets/img/blog/2017/12 folder.
=> away week prague blog post and associated images

assets/js/request-demo.js
Wrap snowplow call in try/catch in form submission to prevent failures due to adblockers
=> War room - fix lead form blocked due to adblockers

pages/community/index.html
=> Mnrq 382 community page updates

_posts/2017-12-27-iglu-r7-treskilling-yellow-released/index.md
fixed Iglu R7 blog post url to include correct release date
=> fixed r7 url

_posts/2017-12-27-iglu-r7-treskilling-yellow-released/index.md
Updates Iglu R7 blog post URL to contain correct release date, 12-27
=> Merge Next.snowplowanalytics.com R7 URL fix

_posts/2017-12-28-snowflake-db-release/index.md
adds Snowflake DB loader release post
=> snowflake db loader release post

_posts/2017-12-27-iglu-r7-treskilling-yellow-released/index.md, _posts/2017-12-28-snowflake-db-release/index.md
Publishes Snowflake DB release post to master
=> merging Next.snowplowanalytics.com Snowflake DB release post

_posts/2017-12-28-snowflake-db-release/index.md
updated snowflake DB post url to include correct date
=> fixed snowflake db post url

_posts/2017-12-28-snowflake-db-release/index.md
Updates Snowflake DB release post to include correct date in URL
=> merge Next.snowplowanalytics.com to fix Snowflake db post url

_data/authors.yml
Added Mike H to authors.yml, fixed minor typo in Kostas' spiel.
=> added mike h as an author

_data/authors.yml, pages/blog/authors/kostas.html, pages/blog/authors/mhadam.html
added mhadam.html in pages/blog/authors; fixed Kostas URL
=> added Mike H author page, fixed Kostas URL

_includes/footer.html, index.html
https://github.com/snowplow/snowplowanalytics.com/issues/321 
URLS redirected to homepage until new locations determined.
Copyright updated.
=> url redirects and copyright update

_posts/2018-01-19-introduction-to-product-analytics/index.md, _posts/2018-01-26-product-analytics-part-two/index.md
Fixed links to pt 3 in PA series
=> url formatting fixes

pages/partners/technology/index.html
Partners Page Filter #357 --> Added "all" button
=> Final changes to Partners Page

_posts/2018-02-15-dataflow-runner-0.4.0-released/index.md, _posts/2018-02-16-dataflow-runner-0.4.0-released/index.md
Reverts snowplow/snowplowanalytics.com#536
cc @Mandelliant
=> Revert 536 revert 533 blog/df runner 0.4

_posts/2018-02-16-dataflow-runner-0.4.0-released/index.md, _posts/2018-02-16-interviewing-with-snowplow/index.md
fixed url for interviewing with snowplow
=> Next.snowplowanalytics.com

assets/css/snowplow/_home.scss
=> Logo in footer bug

pages/partners/implementation/index.html
=> Final - Image path fix #460 & #357

_data/case_studies.yml, pages/customers/index.html
Uploaded Anthony’s content for the page.
=> Customer Content Upload

_posts/2018-03-21-building-a-model-for-event-data-as-a-graph/index.md
=> category fix

_posts/2018-04-03-r102-afontova-gora-released-with-emretlrunner-improvements/index.md
- Embed discourse comments
- heading fix
=> R102 update

assets/css/snowplow/_masonry.scss, index.html
This PR changes the homepage to include the Community Section. #290
=> Homepage - Community Section

assets/css/products-insights.scss
This PR includes the Pricing Table back to the Snowplow Insights Page. #573
=> Snowplow Insights - Pricing Table

assets/css/careers.scss, pages/careers/index.html
This PR will style the Careers Page. #618
=> Careers Page - HTML & CSS

_posts/2018-05-10-snowplow-android-tracker-0.7.0-released/index.md
=> link fixes

_posts/2013-01-20-snowplow-hits-202-stars/index.md, pages/products/snowplow-insights/index.html
Removes rogue Inside the Plow blog post
=> Blog category fix

_posts/2013-06-05-tracking-olark-chat-events-with-snowplow/index.md, _posts/2013-07-10-help-us-build-out-the-snowplow-total-cost-of-ownership-model/index.md, _posts/2014-01-20-the-three-eras-of-business-data-processing/index.md, _posts/2014-03-19-snowplow-and-looker-announce-formal-partnership/index.md, _posts/2014-04-16-identity-stitching-snowplow-vs-google-universal-analytics-kissmetrics-and-mixpanel/index.md, _posts/2014-07-11-on-the-benefits-of-configurable-schemas/index.md, _posts/2018-05-04-mobile-tracking-is-important/index.md
=> updates blog posts with confirmed correct image tag

assets/css/landing-page-v2.scss, assets/css/landing-page-v3.scss, assets/css/landing-page.scss, pages/landing-page-v2/index.html, pages/landing-page-v3/index.html, pages/landing-page/index.html
=> ebook Landing Page

_posts/2018-08-21-r109-lambaesis-real-time-pipeline-upgrade/index.md, pages/products/snowplow-insights/index.html
fixes url for `contact us` button under Snowplow Insights Enterprise pricing to the correct contact form path
=> Insights enterprise contact button fix

_posts/2018-08-29-iglu-r10-released/index.md
Hey @Mandelliant, can we please add this quite important note to the post?
=> Add upgrade note

_posts/2018-09-12-r110-valle-dei-templi-gcp-real-time-pipeline/index.md
switches title and short title
=> R110 title fix

_data/authors.yml, pages/blog/authors/andrzej.html
adds Andrzej author page & info
=> andrzej author page and author yml

google77dd7e98953f61ef.html, googled938a904c3102eb5.html
Removed old Google Site Verification file and replaced it with the new.
=> Google Search Console

assets/css/snowplow/_footer.scss, assets/css/snowplow/_same-height.scss, assets/css/snowplow/_side-by-side.scss, index.html, pages/products/index.html
Hi @Mandelliant, I've just ended fixing some of the issues Hugo had found in the removel of React from the website. 
It's just minor things such as rounded corners on the green boxes and some paddings in mobile and tablet views.
=> Mnrq react removal

_compress_images_cache.yml, index.html, pages/request-demo/index.html
=> updates homepage events and marks required fields on demo form

assets/js/core.js, pages/company/contact-us/index.html
Hi Anthony, here's the Contact us page fixes.
=> Mnrq contact us fixes

assets/js/core.js, pages/company/contact-us/index.html
Reverts snowplow/snowplowanalytics.com#951
=> Revert "Mnrq contact us fixes"

README.md, pages/careers/index.html, pages/products/snowplow-insights/index.html
* Copy update on Snowplow Insights page
* URL fix on snowplowanalytics.com README
* Add open CV collection copy to Careers page
=> insights, readme, careers fixes

_posts/2019-02-13-snowplow-scala-analytics-sdk-0.4.0-released/index.md
Please assign me to review once ready, @rzats
=> Add Scala Analytics SDK 0.4.0 post

pages/products/snowplow-react/index.html
Reverts snowplow/snowplowanalytics.com#1086
=> Revert "remove react pages"

_compress_images_cache.yml, _posts/2019-04-24-data-science-festival-machine-learning-in-real-time/index.md, _posts/2019-04-24-data-science-festival-what-makes-an-effective-data-team/index.md
Machine learning in RT, incl Slideshare embed
What makes an effective data team, incl Slideshare + YouTube embed
=> dsf-blog-posts-by-alex

_includes/footer.html
=> footer fix

pages/customers/index.html, pages/data-quality/index.html, pages/data-richness/index.html, pages/flexibility/index.html, pages/ownership/index.html, pages/partners/index.html, pages/products/snowplow-insights/index.html, pages/products/snowplow-open-source/index.html, pages/products/technology/index.html, pages/real-time/index.html
Added titles and descriptions to
Snowplow Insights
Technology
Customers
Partners
USPs x 5
Open Source
=> titles-descriptions-fd

_posts/2019-05-06-snowplow-objc-tracker-1.1.0-released/index.md, pages/about-us/index.html, pages/get-started/index.html, pages/get-started/thank-you-info/index.html, pages/get-started/thank-you-sales/index.html
link fix in iOS tracker release
title + description fixes
about us page fixes
=> small-fixes-fd

assets/css/casestudy.scss, assets/css/snowplow.scss
=> updated Links color

assets/css/snowplow/_careers.scss, assets/css/snowplow/_revamp.scss, package-lock.json, package.json
=> Jekyll stage3
